export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_API_KEY: 'INVALID_API_KEY',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Wallet
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',

  // Payments
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',

  // OTP
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',

  // SMS
  SMS_PROVIDER_ERROR: 'SMS_PROVIDER_ERROR',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',

  // Onboarding
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',

  // Affiliate / referral
  ALREADY_A_PARTNER: 'ALREADY_A_PARTNER',
  NOT_A_PARTNER: 'NOT_A_PARTNER',
  PARTNER_SUSPENDED: 'PARTNER_SUSPENDED',
  PAYOUT_WINDOW_CLOSED: 'PAYOUT_WINDOW_CLOSED',
  PAYOUT_THRESHOLD_NOT_MET: 'PAYOUT_THRESHOLD_NOT_MET',
  PAYOUT_MIN_BALANCE_NOT_MET: 'PAYOUT_MIN_BALANCE_NOT_MET',
  PAYOUT_PENDING_EXISTS: 'PAYOUT_PENDING_EXISTS',
  PAYOUT_NOT_FOUND: 'PAYOUT_NOT_FOUND',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
